#git aliases
alias gst='git status -sb'
alias gca='git commit -av'
alias gb='git branch --color'
alias gco='git checkout'
alias grv='git remote -v'
alias grst='git reset --hard HEAD'
alias gcl='git clone'
alias gad='git add .'
alias gp='git push'
